export default defineEventHandler(() => {
  return [
    {
      bookingId: 1,
      travelId: 1,
      customerName: "John Doe",
      email: "john@example.com",
      phoneNumber: "1234567890",
      age: 30,
      gender: "Male",
      paymentType: "Credit Transfer",
      notes: "Looking forward to the travel!",
    },
    {
      bookingId: 2,
      travelId: 2,
      customerName: "Jane Smith",
      email: "jane@example.com",
      phoneNumber: "0987654321",
      age: 25,
      gender: "Female",
      paymentType: "Paypal",
      notes: "Please arrange vegetarian meals.",
    },
    {
      bookingId: 3,
      travelId: 3,
      customerName: "Alice Johnson",
      email: "alice@example.com",
      phoneNumber: "1122334455",
      age: 28,
      gender: "Female",
      paymentType: "Revolut",
      notes: "Need a room with a sea view.",
    },
    {
      bookingId: 4,
      travelId: 4,
      customerName: "Bob Brown",
      email: "bob@example.com",
      phoneNumber: "6677889900",
      age: 40,
      gender: "Male",
      paymentType: "Credit Transfer",
      notes: "I will be arriving a day earlier.",
    },
    {
      bookingId: 5,
      travelId: 5,
      customerName: "Charlie Davis",
      email: "charlie@example.com",
      phoneNumber: "5566778899",
      age: 35,
      gender: "Male",
      paymentType: "Paypal",
      notes: "Requesting airport pickup.",
    },
    {
      bookingId: 6,
      travelId: 6,
      customerName: "David Evans",
      email: "david@example.com",
      phoneNumber: "9988776655",
      age: 32,
      gender: "Male",
      paymentType: "Revolut",
      notes: "Will there be Wi-Fi available?",
    },
    {
      bookingId: 7,
      travelId: 7,
      customerName: "Eve Foster",
      email: "eve@example.com",
      phoneNumber: "4433221100",
      age: 29,
      gender: "Female",
      paymentType: "Credit Transfer",
      notes: "I have dietary restrictions.",
    },
    {
      bookingId: 8,
      travelId: 8,
      customerName: "Frank Green",
      email: "frank@example.com",
      phoneNumber: "7766554433",
      age: 45,
      gender: "Male",
      paymentType: "Paypal",
      notes: "Is there a laundry service?",
    },
    {
      bookingId: 9,
      travelId: 9,
      customerName: "Grace Harris",
      email: "grace@example.com",
      phoneNumber: "5544332211",
      age: 27,
      gender: "Female",
      paymentType: "Revolut",
      notes: "Can I bring my pet?",
    },
    {
      bookingId: 10,
      travelId: 10,
      customerName: "Hank Ivy",
      email: "hank@example.com",
      phoneNumber: "6655443322",
      age: 34,
      gender: "Male",
      paymentType: "Credit Transfer",
      notes: "Need a room with two beds.",
    },
    {
      bookingId: 11,
      travelId: 11,
      customerName: "Ivy Johnson",
      email: "ivy@example.com",
      phoneNumber: "7766554433",
      age: 42,
      gender: "Female",
      paymentType: "Paypal",
      notes: "Can I get a guide?",
    },
    {
      bookingId: 12,
      travelId: 12,
      customerName: "Jack King",
      email: "jack@example.com",
      phoneNumber: "3344556677",
      age: 38,
      gender: "Male",
      paymentType: "Revolut",
      notes: "Will there be translators available?",
    },
    {
      bookingId: 13,
      travelId: 13,
      customerName: "Karen Lee",
      email: "karen@example.com",
      phoneNumber: "4455667788",
      age: 36,
      gender: "Female",
      paymentType: "Credit Transfer",
      notes: "Are there child-friendly activities?",
    },
    {
      bookingId: 14,
      travelId: 14,
      customerName: "Larry Moore",
      email: "larry@example.com",
      phoneNumber: "5566778899",
      age: 44,
      gender: "Male",
      paymentType: "Paypal",
      notes: "Will there be first aid available?",
    },
    {
      bookingId: 15,
      travelId: 15,
      customerName: "Mona Neal",
      email: "mona@example.com",
      phoneNumber: "6677889900",
      age: 30,
      gender: "Female",
      paymentType: "Revolut",
      notes: "Can I book an additional tour?",
    },
    {
      bookingId: 16,
      travelId: 16,
      customerName: "Nancy O'Brien",
      email: "nancy@example.com",
      phoneNumber: "7788990011",
      age: 33,
      gender: "Female",
      paymentType: "Credit Transfer",
      notes: "What is the refund policy?",
    },
    {
      bookingId: 17,
      travelId: 17,
      customerName: "Oscar Perry",
      email: "oscar@example.com",
      phoneNumber: "8899001122",
      age: 37,
      gender: "Male",
      paymentType: "Paypal",
      notes: "Can I upgrade my room?",
    },
    {
      bookingId: 18,
      travelId: 18,
      customerName: "Pat Quinn",
      email: "pat@example.com",
      phoneNumber: "9900112233",
      age: 29,
      gender: "Male",
      paymentType: "Revolut",
      notes: "Will there be a shuttle service?",
    },
    {
      bookingId: 19,
      travelId: 19,
      customerName: "Quincy Ross",
      email: "quincy@example.com",
      phoneNumber: "0011223344",
      age: 41,
      gender: "Male",
      paymentType: "Credit Transfer",
      notes: "Can I book a spa session?",
    },
    {
      bookingId: 20,
      travelId: 20,
      customerName: "Rachel Smith",
      email: "rachel@example.com",
      phoneNumber: "1122334455",
      age: 35,
      gender: "Female",
      paymentType: "Paypal",
      notes: "Will there be a photographer available?",
    },
  ];
});
