export default defineEventHandler(() => {
  return [
    {
      travelId: 1,
      travelTitle: "Himalayan Adventure",
      price: 1200,
      departureDate: "2024-07-01",
      returnDate: "2024-07-10",
      userRating: 4.8,
      description: "An exciting journey through the Himalayas.",
      location: "Nepal",
      imageUrl: "https://source.unsplash.com/random/?nepal",
    },
    {
      travelId: 2,
      travelTitle: "Safari in Kenya",
      price: 2500,
      departureDate: "2024-08-15",
      returnDate: "2024-08-25",
      userRating: 4.9,
      description: "Experience the wildlife in Kenya.",
      location: "Kenya",
      imageUrl: "https://source.unsplash.com/random/?Kenya",
    },
    {
      travelId: 3,
      travelTitle: "Beach Getaway in Maldives",
      price: 3000,
      departureDate: "2024-09-05",
      returnDate: "2024-09-15",
      userRating: 4.7,
      description: "Relax on the pristine beaches of Maldives.",
      location: "Maldives",
      imageUrl: "https://source.unsplash.com/random/?Maldives",
    },
    {
      travelId: 4,
      travelTitle: "European Tour",
      price: 4000,
      departureDate: "2024-10-10",
      returnDate: "2024-10-20",
      userRating: 4.6,
      description: "Discover the beauty of Europe.",
      location: "Europe",
      imageUrl: "https://source.unsplash.com/random/?Europe",
    },
    {
      travelId: 5,
      travelTitle: "Japanese Cultural travel",
      price: 3500,
      departureDate: "2024-11-01",
      returnDate: "2024-11-10",
      userRating: 4.8,
      description: "Experience the rich culture of Japan.",
      location: "Japan",
      imageUrl: "https://source.unsplash.com/random/?Japan",
    },
    {
      travelId: 6,
      travelTitle: "Australian Outback Expedition",
      price: 4500,
      departureDate: "2024-12-01",
      returnDate: "2024-12-10",
      userRating: 4.7,
      description: "Explore the rugged beauty of the Australian Outback.",
      location: "Australia",
      imageUrl: "https://source.unsplash.com/random/?Australia",
    },
    {
      travelId: 7,
      travelTitle: "Amazon Rainforest Adventure",
      price: 2000,
      departureDate: "2024-05-01",
      returnDate: "2024-05-10",
      userRating: 4.5,
      description: "Journey into the heart of the Amazon rainforest.",
      location: "Brazil",
      imageUrl: "https://source.unsplash.com/random/?Brazil",
    },
    {
      travelId: 8,
      travelTitle: "Alaskan Cruise",
      price: 5000,
      departureDate: "2024-06-01",
      returnDate: "2024-06-10",
      userRating: 4.9,
      description:
        "Experience the stunning scenery of Alaska on a luxury cruise.",
      location: "USA",
      imageUrl: "https://source.unsplash.com/random/?USA",
    },
    {
      travelId: 9,
      travelTitle: "Egyptian Pyramids Tour",
      price: 1500,
      departureDate: "2024-04-01",
      returnDate: "2024-04-10",
      userRating: 4.6,
      description: "Explore the ancient pyramids of Egypt.",
      location: "Egypt",
      imageUrl: "https://source.unsplash.com/random/?Egypt",
    },
    {
      travelId: 10,
      travelTitle: "South African Safari",
      price: 2500,
      departureDate: "2024-07-15",
      returnDate: "2024-07-25",
      userRating: 4.8,
      description: "Witness the Big Five in their natural habitat.",
      location: "South Africa",
      imageUrl: "https://source.unsplash.com/random/?South Africa",
    },
    {
      travelId: 11,
      travelTitle: "New Zealand Adventure",
      price: 3500,
      departureDate: "2024-08-01",
      returnDate: "2024-08-10",
      userRating: 4.7,
      description: "Explore the stunning landscapes of New Zealand.",
      location: "New Zealand",
      imageUrl: "https://source.unsplash.com/random/?New Zealand",
    },
    {
      travelId: 12,
      travelTitle: "Patagonia Hiking travel",
      price: 3000,
      departureDate: "2024-09-01",
      returnDate: "2024-09-10",
      userRating: 4.9,
      description: "Hike through the breathtaking landscapes of Patagonia.",
      location: "Chile",
      imageUrl: "https://source.unsplash.com/random/?Chile",
    },
    {
      travelId: 13,
      travelTitle: "Iceland Northern Lights Tour",
      price: 2000,
      departureDate: "2024-10-01",
      returnDate: "2024-10-10",
      userRating: 4.8,
      description: "Experience the magical Northern Lights in Iceland.",
      location: "Iceland",
      imageUrl: "https://source.unsplash.com/random/?Iceland",
    },
    {
      travelId: 14,
      travelTitle: "Peru Inca Trail",
      price: 1800,
      departureDate: "2024-11-01",
      returnDate: "2024-11-10",
      userRating: 4.7,
      description: "Hike the famous Inca Trail to Machu Picchu.",
      location: "Peru",
      imageUrl: "https://source.unsplash.com/random/?Peru",
    },
    {
      travelId: 15,
      travelTitle: "Canadian Rockies Expedition",
      price: 4000,
      departureDate: "2024-12-01",
      returnDate: "2024-12-10",
      userRating: 4.9,
      description: "Explore the majestic Canadian Rockies.",
      location: "Canada",
      imageUrl: "https://source.unsplash.com/random/?Canada",
    },
    {
      travelId: 16,
      travelTitle: "Greek Island Hopping",
      price: 3000,
      departureDate: "2024-05-01",
      returnDate: "2024-05-10",
      userRating: 4.8,
      description: "Sail through the beautiful Greek Islands.",
      location: "Greece",
      imageUrl: "https://source.unsplash.com/random/?Greece",
    },
    {
      travelId: 17,
      travelTitle: "Thailand Beach Retreat",
      price: 2500,
      departureDate: "2024-06-01",
      returnDate: "2024-06-10",
      userRating: 4.7,
      description: "Relax on the stunning beaches of Thailand.",
      location: "Thailand",
      imageUrl: "https://source.unsplash.com/random/?Thailand",
    },
    {
      travelId: 18,
      travelTitle: "Antarctic Expedition",
      price: 6000,
      departureDate: "2024-07-01",
      returnDate: "2024-07-10",
      userRating: 4.9,
      description: "Embark on a once-in-a-lifetime journey to Antarctica.",
      location: "Antarctica",
      imageUrl: "https://source.unsplash.com/random/?Antarctica",
    },
    {
      travelId: 19,
      travelTitle: "Galapagos Islands Adventure",
      price: 4500,
      departureDate: "2024-08-01",
      returnDate: "2024-08-10",
      userRating: 4.8,
      description: "Discover the unique wildlife of the Galapagos Islands.",
      location: "Ecuador",
      imageUrl: "https://source.unsplash.com/random/?Ecuador",
    },
    {
      travelId: 20,
      travelTitle: "Paris and Rome City Tour",
      price: 3500,
      departureDate: "2024-09-01",
      returnDate: "2024-09-10",
      userRating: 4.7,
      description: "Explore the iconic cities of Paris and Rome.",
      location: "France and Italy",
      imageUrl: "https://source.unsplash.com/random/?France and Italy",
    },
  ];
});
